package com.qiumuzi.VisualizeSong.Model;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.id
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.name
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.id
     *
     * @return the value of Account.id
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.id
     *
     * @param id the value for Account.id
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.name
     *
     * @return the value of Account.name
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.name
     *
     * @param name the value for Account.name
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}