package com.qiumuzi.VisualizeSong.Mapper;

import com.qiumuzi.VisualizeSong.Model.Account;
import com.qiumuzi.VisualizeSong.Model.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    long countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    Account selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated Mon May 25 21:37:11 EDT 2020
     */
    int updateByPrimaryKey(Account record);
}